# Generated by Django 5.2.2 on 2025-06-13 09:47

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entrepreneurs', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InvoiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Наименование товара/услуги')),
                ('quantity', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Количество')),
                ('unit', models.CharField(max_length=20, verbose_name='Единица измерения')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена за единицу')),
                ('vat_rate', models.DecimalField(decimal_places=2, default=0, max_digits=4, verbose_name='Ставка НДС (%)')),
            ],
            options={
                'verbose_name': 'Позиция счёта',
                'verbose_name_plural': 'Позиции счёта',
            },
        ),
        migrations.CreateModel(
            name='BankDetails',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('bank_name', models.CharField(max_length=255, verbose_name='Название банка')),
                ('bik', models.CharField(max_length=9, validators=[django.core.validators.RegexValidator('^\\d{9}$', 'БИК должен содержать ровно 9 цифр')], verbose_name='БИК')),
                ('correspondent_account', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{20}$', 'Корреспондентский счёт должен содержать ровно 20 цифр')], verbose_name='Корреспондентский счёт')),
                ('payment_account', models.CharField(max_length=20, validators=[django.core.validators.RegexValidator('^\\d{20}$', 'Расчётный счёт должен содержать ровно 20 цифр')], verbose_name='Расчётный счёт')),
                ('entrepreneur', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bank_details', to='entrepreneurs.entrepreneurprofile', verbose_name='Предприниматель')),
            ],
            options={
                'verbose_name': 'Банковские реквизиты',
                'verbose_name_plural': 'Банковские реквизиты',
            },
        ),
        migrations.CreateModel(
            name='GeneratedDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_type', models.CharField(max_length=50, verbose_name='Тип документа')),
                ('file', models.FileField(upload_to='documents/%Y/%m/%d/', verbose_name='Файл')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('entrepreneur', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='documents', to='entrepreneurs.entrepreneurprofile', verbose_name='Предприниматель')),
            ],
            options={
                'verbose_name': 'Сгенерированный документ',
                'verbose_name_plural': 'Сгенерированные документы',
                'ordering': ['-created_at'],
            },
        ),
    ]
